external_components:
  - source: github://htumanyan/esphome-navien@main
    components:
      - navien

time:
  - platform: homeassistant

web_server:
  version: 3

captive_portal:

api:

ota:
  - platform: esphome

logger:
  level: INFO

uart:
  id: main_hw_uart
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 19200
  stop_bits: 1
  parity: NONE
  rx_buffer_size: 8192

sensor:
  - platform: navien
    id: navien_main
    src: 0
    name: ${friendly_name} Metrics
    uart_id: main_hw_uart
    dhw_set_temperature:
      name: ${friendly_name} DHW Set Temp
      entity_category: diagnostic
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: °F
    inlet_temperature:
      name: ${friendly_name} Inlet Temp
      entity_category: diagnostic
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: °F
    outlet_temperature:
      name: ${friendly_name} Outlet Temp
      entity_category: diagnostic
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: °F
    water_flow:
      name: ${friendly_name} Water Flow
      entity_category: diagnostic
      filters:
        - lambda: return x / 3.785;
      unit_of_measurement: GPM
    water_utilization:
      name: ${friendly_name} Water Capacity Utilization
      entity_category: diagnostic
      unit_of_measurement: '%'
    heat_capacity:
      name: ${friendly_name} Heat Capacity
      entity_category: diagnostic
      unit_of_measurement: '%'
      accuracy_decimals: 1
    gas_total:
      id: gas_total_therms
      name: ${friendly_name} Accumulated Gas Usage
      entity_category: diagnostic
      filters:
        - lambda: return x * 9131.0 / 25193.0 / 10.0;
      unit_of_measurement: Therms
      accuracy_decimals: 1
    gas_current:
      id: gas_current_btu
      name: ${friendly_name} Current Gas Usage
      entity_category: diagnostic
      filters:
        - lambda: return x * 3.9680;
      unit_of_measurement: BTU
      accuracy_decimals: 1
    conn_status:
      name: ${friendly_name} Connection Status
      entity_category: diagnostic
    boiler_active:
      name: ${friendly_name} Boiler Active
      entity_category: diagnostic
    recirc_running:
      name: ${friendly_name} Recirculation Running
      entity_category: diagnostic
    recirc_mode:
      name: ${friendly_name} Recirculation Mode
      entity_category: diagnostic
    error_code:
      name: ${friendly_name} Error Code
      entity_category: diagnostic
    error_level:
      name: ${friendly_name} Error Level
      entity_category: diagnostic

  - platform: copy
    source_id: gas_total_therms
    name: ${friendly_name} Accumulated Gas Usage CCF
    entity_category: diagnostic
    unit_of_measurement: CCF
    device_class: gas
    state_class: total_increasing
    filters:
      - lambda: return x / 1.038;
    accuracy_decimals: 1
    disabled_by_default: true

  - platform: copy
    source_id: gas_current_btu
    name: ${friendly_name} Current Gas Usage kW
    entity_category: diagnostic
    unit_of_measurement: kW
    device_class: power
    state_class: measurement
    filters:
      - lambda: return x * 10.0 / 3412.0;
    accuracy_decimals: 1
    disabled_by_default: true

text_sensor:
  - platform: navien
    navien: navien_main
    name: ${friendly_name} Operating State
    entity_category: diagnostic
    operating_state: true
  - platform: navien
    navien: navien_main
    name: ${friendly_name} Heating Mode
    entity_category: diagnostic
    heating_mode: true

switch:
  - platform: navien
    navien: navien_main
    type: power
    name: ${friendly_name} Main Power
    entity_category: diagnostic
    id: main_power

button:
  - platform: navien
    name: ${friendly_name} Hot Button
  - platform: restart
    name: ${device_name} Restart
  - platform: safe_mode
    name: Flash Device (Safe Mode)
    icon: mdi:cellphone-arrow-down
    id: safe_mode_button

water_heater:
  - platform: navien
    navien: navien_main
    id: navien_water_heater
    visual:
      min_temperature: 98F
      max_temperature: 125F
      target_temperature_step: 1
    name: ${friendly_name}
