# Basic Config

substitutions:
  #   # https://esphome.io/guides/configuration-types.html#substitutions
  #device_name: navien-heater # hostname & entity_id
  #friendly_name: "Navien Gas Heater" # Displayed in HA frontend
  project_name: Navien.esp8266
  project_version: "0.0.0.1"

packages:
  navien: !include navien-base.yml

logger:
#  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart to avoid interference
               # with sending/receiving over the UART port on ESP8266

  hardware_uart: UART1 # redirect logs to UART1 GPIO2 to avoid conflicts
                       # with the MCU communication through the main hardware UART

  # https://esphome.io/components/logger
  level: INFO
  esp8266_store_log_strings_in_flash: false
  
switch:
  - platform: gpio
    id: hot_button
    pin: D5
    name: "Navien Enable Hot Button"
    restore_mode: RESTORE_DEFAULT_ON


button:
  - platform: template
    name: "Navien Hot Button"
    on_press:
    - switch.turn_off: hot_button
    - delay: 1000ms
    - switch.turn_on: hot_button

