substitutions:
  name: navien-heater
  friendly_name: Navien

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret esp_wifi_ssid
  password: !secret esp_wifi_password
  domain: !secret esp_wifi_domain

packages:
  Navien.ATOM-Lite-ESP32: github://htumanyan/navien/esphome/navien-esphome-atom-lite-esp32.yml

api:
  encryption:
    key: !secret esp_api_key

ota:
  - password: !secret esp_ota_password
    platform: esphome

web_server:
  ota: false
  auth:
    username: !secret esp_web_user
    password: !secret esp_web_password
