#
# This file is to be included if you are building from
# HA ESP Home builder (as opposed to a local command line build from the terminal).
# It is set to build for D1 Mini board by default. If you hardware is ESP32 Atom or other
# then uncomment the relevant line under "files" and comment all others

substitutions:
  device_name: navien-heater # hostname & entity_id
  friendly_name: "Navien" # Displayed in HA frontend
  git_home: https://github.com/htumanyan/navien
  external_component_source: ${git_home}

packages:
  navien:
    url: ${git_home}
    ref: main    # optional
    files:
#      - path: esphome/navien-d1-mini.yml
      - path: esphome/navien-esphome-atom-lite-esp32.yml

dashboard_import:
  package_import_url: ${git_home}
  import_full_config: true
